# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cooking_pb2 as cooking__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cooking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CookingAdvisorStub(object):
    """做菜咨询服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCookingAdvice = channel.unary_unary(
                '/cooking.CookingAdvisor/GetCookingAdvice',
                request_serializer=cooking__pb2.CookingRequest.SerializeToString,
                response_deserializer=cooking__pb2.CookingResponse.FromString,
                _registered_method=True)
        self.GetCookingAdviceStream = channel.unary_stream(
                '/cooking.CookingAdvisor/GetCookingAdviceStream',
                request_serializer=cooking__pb2.CookingRequest.SerializeToString,
                response_deserializer=cooking__pb2.CookingResponse.FromString,
                _registered_method=True)


class CookingAdvisorServicer(object):
    """做菜咨询服务
    """

    def GetCookingAdvice(self, request, context):
        """获取做菜建议
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCookingAdviceStream(self, request, context):
        """流式获取做菜建议
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CookingAdvisorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCookingAdvice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCookingAdvice,
                    request_deserializer=cooking__pb2.CookingRequest.FromString,
                    response_serializer=cooking__pb2.CookingResponse.SerializeToString,
            ),
            'GetCookingAdviceStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCookingAdviceStream,
                    request_deserializer=cooking__pb2.CookingRequest.FromString,
                    response_serializer=cooking__pb2.CookingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cooking.CookingAdvisor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cooking.CookingAdvisor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CookingAdvisor(object):
    """做菜咨询服务
    """

    @staticmethod
    def GetCookingAdvice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cooking.CookingAdvisor/GetCookingAdvice',
            cooking__pb2.CookingRequest.SerializeToString,
            cooking__pb2.CookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCookingAdviceStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cooking.CookingAdvisor/GetCookingAdviceStream',
            cooking__pb2.CookingRequest.SerializeToString,
            cooking__pb2.CookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
